### ISSUE TITLE
Windows Defender Detects XiebroC2 Build Instantly

### ISSUE THREAD

**Issue by 0x1x02** [INotGreen/XiebroC2#20]
Hello ! @INotGreen 

I wanted to congratulate you on the remarkable work you've done with the XiebroC2 project. It's truly impressive and showcases your expertise in this field. However, I've encountered an issue where Windows Defender instantly detects the build, which could potentially hinder its adoption among users. I understand that antivirus detection can be challenging, but addressing this issue could greatly benefit the project's usability. Thank you for your dedication to this project, and I look forward to seeing how it progresses in the future.

Best regards,

0x1x02

**Comment by INotGreen** [comment]
Thanks bro, what I'm trying to say is that the reason it was detected by Defender is because I obfuscated the Controller and Teamserver with UPX compression, which made the program smaller, but Windows defender apparently detects it, and with The abuse of XiebroC2 is more AV/EDR will make a counter to it, finally if you are not confident about the security of the program you can use it in a virtual machine, for the sake of my reputation, I mustn't be in it Place a backdoor
